- name: Control panel NFS install
  hosts: control-plane
  become_method: sudo
  vars:
    playbookfolder: '/Linux'
    script_folder: ''
  tasks:
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'nfs/nfs.sh'
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'nfs/helm.sh'
    - include_tasks: '{{ playbookfolder }}/install.yaml'
- name: Docker, nfs-common installation
  hosts: control-plane,worker
  become_method: sudo
  vars:
    playbookfolder: '/Linux'
    script_folder: ''
  tasks:
    - include_tasks: '{{ playbookfolder }}/install.yaml'
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'nfs/nfs-common.sh'
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'Docker/docker-install.sh'
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'Docker/docker-configure.sh'
