- name: script install
  hosts: control-plane
  become_method: sudo
  vars:
    playbookfolder: '/Linux'
    #script_folder: ''
  tasks:
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        #bash_script: 'test.sh'
        bash_script: 'helm/mosquitto.sh'
